### ISSUE TITLE
Dead lock for dehazenet_options.py

### ISSUE THREAD

**Issue by Seanforfun** [Seanforfun/Deep-Learning#4]

**Comment by Seanforfun** [comment]
I started a conditional block at the beginning of consumer, and every time producer put a task into the task queue, it will release all the consumers which are waiting.
However, if the number tasks not enough, the producers are finished before Consumer threads are created, so the consumer is blocked forever.
I removed the conditional lock and let the main thread sleep for 0.0001 second between producer and consumer. So we can make sure producer threads are created before consumers.
* [dehazenet_options.py](https://github.com/Seanforfun/Deep-Learning/blob/master/DehazeNet/dehazenet_options.py)

**Comment by noobgrow** [comment]
hello!
Could u please provide the training dataset?Or where  can I get it?
thanks for your help!

**Comment by Seanforfun** [comment]
> 
> 
> hello!
> Could u please provide the training dataset?Or where can I get it?
> thanks for your help!

Hello,
The training dataset is from a paper [Benchmarking Single Image Dehazing and Beyond](https://arxiv.org/abs/1712.04143).
You can download the dataset from their [website](https://sites.google.com/view/reside-dehaze-datasets/reside-standard?authuser=0). I download the data and generate my own tf-record file.
You questions doesn't match this issue so if you have any further questions please re-open an new issue for making everything clear. 😄 
Regards.
