### ISSUE TITLE
关于make3D数据集的真实深度图

### ISSUE THREAD

**Issue by Zwt-mao** [Seanforfun/Deep-Learning#8]
您好！我现在需要make3D数据集的真实深度图用以训练我的模型，但是官方提供的是.mat文件，尝试转换为图片格式后效果极差，也可能是我的转换方法不对？不知道有没有办法获取到make3d中的真实深度图？感谢您的指导！

**Comment by Seanforfun** [comment]
Thank you for your question.

I am not familiar with the make3D database you mentioned. And also I think we didn't use that database as a datapoint in our paper.

You can try to contact with the creator of that database for a precise anwser.
